### ISSUE TITLE
Why does this install minecraft through proton when native minecraft exists?

### ISSUE THREAD

**Issue by PartyWumpus** [moraroy/NonSteamLaunchers-On-Steam-Deck#142]
Java minecraft works perfectly fine when run natively with the [normal launcher on Flathub](https://flathub.org/apps/com.mojang.Minecraft) (or with a 3rd party launcher like prism), so why would you install it like this?

I found someone testing it, and minecraft through wine has significantly degraded performance: https://flightlessmango.com/games/13928/logs/1920 (test is from 2 years ago)

**Comment by moraroy** [comment]
@PartyWumpus just to stay in nature and concept with the script. The script installs ge proton and uses that as a layer to install the launchers. I never wanted to have any flat packs on this script because people can go install that themselves. I made this script for the layman that doesn't know a thing about Linux or computers and just wants to play. So I kept that version of mine craft.
