### ISSUE TITLE
Black Window in EGS launcher from Game Mode

### ISSUE THREAD

**Issue by officialAbdii** [moraroy/NonSteamLaunchers-On-Steam-Deck#155]
Hi, firstly great work on this script. Thank you so much.

I tried running Epic on Desktop mode and it ran perfectly. It took a while for it to load my library but after that it was working.

When i am launching it in gaming mode after adding it as a non steam game, i can see the initial EGS loading screen that we see on windows with a loading bar at the bottom, and after that i only see a black window. I am hovering the mouse and i notice that there are selectable option on the black window as the cursor changes as i scroll around but its just a black window. I am using proton 8.25

**Comment by chasehundreds** [comment]
Wow still no update from creator. I'm also having this issue.

**Comment by moraroy** [comment]
@officialAbdii @chasehundreds dont worry brother im on the case... are you both using the new Oled? and also just to let you know, you need to allow Epic Games to install its epic game services in order to use the launcher. make sure the shortcut that is created for Epic Games Launcher is using -opengl in the Start In Directory of the Epic Games Shortcut, my script should already be doing this.
