### ISSUE TITLE
Path not found error installing EA App

### ISSUE THREAD

**Issue by sysmoon14** [moraroy/NonSteamLaunchers-On-Steam-Deck#172]
Trying to install the EA App and I'm getting a "Path not found" error message pop-up.

**Comment by moraroy** [comment]
@sysmoon14 yeah usually that fixes a lot at the expense of deleting games... maybe try using the Uninstall button that may fix a particular one... I know currently in the script there is a weird bug that happens if you were to select like 6 launchers in a row to download the script exits after Amazon or EA App for some reason I still have to fix that.

**Comment by AadilF1** [comment]
This is a workaround rather than a fix, I'm having this issue, "starting fresh" is not a solution. I'm currently going through this and unable to use the EA app, it worked fine for a while after starting fresh, but then I got the EA updater message at which point it no longer works, so I uninstalled EA app through Nonsteamlaunchers and tried reinstalling, but getting the path not found error.
