### ISSUE TITLE
Shortcuts are re-added when script is run for second time. 

### ISSUE THREAD

**Issue by ddutchie** [moraroy/NonSteamLaunchers-On-Steam-Deck#20]
Thanks for this! It really makes a difference to how quickly one can add these launchers to your SteamDeck.

Small Issue:
I used the script to install Battle.net and Epic Games. I then later ran the script to add Origin and the Battle.net and Epic Games shortcuts were re-added to Steam and I had two shortcuts for these two launchers.

**Comment by moraroy** [comment]
@ddutchie it's most likely because you clicked "separate app ids" it will only make shortcuts to your library if the path is different because it's a different epic games launcher for example. One shortcut would say NonSteamLaunchers the other would probably say EpicGamesLauncher in the compatdata folder. Therefore two shortcuts of the same name but different app id's hence it looks like the same. Unless you're able to show me a log I think that's what happened.
