### ISSUE TITLE
Add a download button for lay users in the Readme file

### ISSUE THREAD

**Issue by Heus-Sueh** [moraroy/NonSteamLaunchers-On-Steam-Deck#33]
same as decky-loader Readme button
we could ask if we can use this image of them
![image](https://github.com/moraroy/NonSteamLaunchers-On-Steam-Deck/assets/98482469/33f31d3d-9a69-4fca-a928-207a5d17a98f)

Decky Loader Readme [RAW](https://raw.githubusercontent.com/SteamDeckHomebrew/decky-loader/main/README.md)

**Comment by moraroy** [comment]
Thank you @Heus-Sueh for the suggestion! @cchrkk what do you think should we add that? 
Also thank you brother for the Kofi! I saw it on my email you didn't have to! I should be giving you the cup of coffee lol. Another thing on my mind as well, the log file is good I like it makes it very easy but I noticed a problem. I ran the script like 20 times yesterday trying to test some things and I noticed the log file "builds" and gets bigger with code. When steam restarts the log seems to keep logging even after the script is finished. It may be because I need to put an "exit" at the end of the script not sure if that's the problem or not... what do you think?

**Comment by cchrkk** [comment]
Here we go 👌👌 https://github.com/moraroy/NonSteamLaunchers-On-Steam-Deck/pull/34
I knew there was a way to make a button to auto download it, i'm too noob to undestand stuff :D 

@moraroy don't worry bro, your script idea is super handy and convenient. You're super invested into fixing issues and implementing stuff and u deserved a coffee 💯 

Try to add _exit_ and see, I know zero of programming not even bash, I'm just a geek 🤣

**Comment by cchrkk** [comment]
I just noticed it's not working anymore, to be able to download the desktop file instead of opening it in the browser, you must link to some file in the Release section. So you probably need to create a new repository and release the .desktop file there, then link it. 😒 Why is it so hard to link and download a file

**Comment by cchrkk** [comment]
Fixed temporarily by #36 but maybe you want to create a DL repository yourself

**Comment by moraroy** [comment]
@cchrkk nice work! Yeah I noticed that too but I'm thinking maybe we won't need the .desktop file anymore since we have that button now.. but in the end I guess the more ways to download the better?

**Comment by moraroy** [comment]
@cchrkk thats a tight logo BRO!!!!! <3

**Comment by cchrkk** [comment]
> @cchrkk nice work! Yeah I noticed that too but I'm thinking maybe we won't need the .desktop file anymore since we have that button now.. but in the end I guess the more ways to download the better?

Uhm, that button is linked to the desktop file 😂 That button didn't work for the last 20 hours.



> @cchrkk thats a tight logo BRO!!!!! <3

Thank you :) spent a good hour for that

**Comment by Heus-Sueh** [comment]
thanks :+1: @cchrkk
