### ISSUE TITLE
Battle.net failing on Update Agent during install

### ISSUE THREAD

**Issue by James-Coyne** [moraroy/NonSteamLaunchers-On-Steam-Deck#73]
Similar to #24, I am experiencing a hang and error on installing Battle.net whenever it reaches the halfway mark on "Updating Battle.net Update Agent.." however the logs don't seem to indicate the process is hanging the same way.
I have ensured no other version of Proton-GE is installed besides the latest (8.4 as of writing) and no packages containing community proton builds are installed through Discovery. 

I've attached screenshots and the [log file](https://github.com/moraroy/NonSteamLaunchers-On-Steam-Deck/files/11807795/NonSteamLaunchers-install.log), are there any other troubleshooting steps I can take?

![Screenshot_20230620_174353](https://github.com/moraroy/NonSteamLaunchers-On-Steam-Deck/assets/3893276/a157750c-cdf8-4b68-b76a-0c314a056a21)
![Screenshot_20230620_174436](https://github.com/moraroy/NonSteamLaunchers-On-Steam-Deck/assets/3893276/ea53e750-c790-4b96-b708-1a3b7d9ac47f)

**Comment by moraroy** [comment]
@James-Coyne https://us.battle.net/support/en/article/19031

**Comment by James-Coyne** [comment]
I've tried rebooting and clearing the half-installed Battle.net through both the script and manually deleting the prefix in compatdata, however the issue persists on every attempt. I'd rather not have to resort to a factory reset to install the launcher if possible.

**Comment by moraroy** [comment]
@James-Coyne hey brother this is an ongoing issue with blizzard even on lutris and other ways that have battlenet installed.... so when it comes to this script unless you have found a sure way to fix this issue there isn't much I can do... what I can say is please don't  wipe your deck because of this issue...this is a blizzard issue not a "system issue."

**Comment by martyn-c-o** [comment]
FYI - Installing Battle.net via the exe manually in Steam will allow the installer to get passed the AgentUpdater stage, so not 100% that this is exclusively a Blizzard issue. Problem is that installing this way, the launcher wont start after initial install?

**Comment by James-Coyne** [comment]
> FYI - Installing Battle.net via the exe manually in Steam will allow the installer to get passed the AgentUpdater stage, so not 100% that this is exclusively a Blizzard issue. Problem is that installing this way, the launcher wont start after initial install?

I've been testing with various methods of install. Lutris can kind of successfully install but it's incredibly slow and laggy. Manual installs "work" but using the launcher after that is a pain/doesn't seem to actually work. It seems only this script fails to get past the Update Agent step.

**Comment by Strugglechen1337** [comment]
So if I understand it right it's an blizzard issue that we cannot update the Battle.net launcher ?

**Comment by moraroy** [comment]
@Strugglechen1337 sort of... it's a mix between their new updates and proton ge as far as I can tell..I could be wrong though, like I said I own overwatch 2 and I'm still able to play even though my launcher says "update"

**Comment by Strugglechen1337** [comment]
Yes I own Diablo 4 and it's working too , he only says update in the left upper corner

**Comment by numbawon** [comment]
I was able to manually install Battle.net after also experiencing the same message/failure as above. 

After several attempts using the script (15 some times) I installed everything but battle.net

From terminal I ran 
WINEPREFIX=/home/deck/.local/share/Steam/steamapps/compatdata/NonSteamLaunchers/pfx/ winetricks

depending on your configuration you may have a different path, if you used SDcard or external drive in any way.

This let me manually run the battle.net installer successfully. As a note for completeness, I tried manually adding battle.net to Steam following the same form as the others that were added via the script but it didn't work. Instead of that, re-run the script, select the battle.net option and click install. It doesn't seem to run the installer actually, likely as it's already installed and no change is needed. It does though add the launcher to Steam and you can then run it and login/install games etc. After this I rebooted just because it made me feel better.

But as with everything, I ran through this sequence twice successfully, YMMV

**Comment by jack-fin** [comment]
I tried to update battle.net before realizing this issue. Now unfortunately I cannot launch it at all. 

I tried uninstalling through the tool and reinstalling but am getting the same update error. Is there anything I can do to get battle.net working again?
