### ISSUE TITLE
Legacy Games launcher - downloads fail

### ISSUE THREAD

**Issue by Localhorst86** [moraroy/NonSteamLaunchers-On-Steam-Deck#8]
With 2.4 finally adding the launchers to the library, I tried installing games from various launchers. Most work fine, but I am struggling installing any games with the Legacy Games Launcher.

Once logged into my account, I can go to my library and see a few games ready to install.

When trying to install a game, though, Legacy Games will instantly error out with

"Download canceled. Please check your internet connection and try again."

Obviously, I am connected to the internet, I can even access the Store, New Releases and Deals section of the launcher.

Has anyone had similar experiences? If so, were you able to rectify the issue?

**Comment by Localhorst86** [comment]
I tried in Gaming Mode as well as Desktop. Both environments had the same issue.

**Comment by moraroy** [comment]
@Localhorst86 ahh interesting ok ill take a look and see what up... i actually dont have a legacy account so i wasnt testing that... but thank you for letting me know ill see what i can do!

**Comment by moraroy** [comment]
@Localhorst86 I may disable Legacy Games and Humble Games Collection for the time being. They dont seem to work without extreme circumstances. Id  rather focus on making things works for the ones that do then tackle these launchers that make things really complicated. Unless anyone can find a way to automate a fix for these launchers. i almsot have Humble games Collection working but.. its requiring some weird workarounds

**Comment by moraroy** [comment]
@DarkenLX I don't have a legacy games account.. but is this still broken?

**Comment by DarkenLX** [comment]
I can check again when i get home but i believe it's something to do internally with wine itself and therefore anything using its current source ( proton etc) i have not been able to figure out what exactly the cause is but there is nothing listed about the app at all on WineHQ. Lutris forms are the only place that anyone mentioned anything about it. And that was back in 2022 ( https://forums.lutris.net/t/legacy-games-launcher/15628 ) for reference. So i don't know maybe not enough people use the launcher for a report to be on WineHQ.

**Comment by moraroy** [comment]
@DarkenLX from what I read it had to do with the downloads of the games not being able to download because some configuration file or something like that I just can't remember where I read that at. It kinda sounded like it was fixable but I'm not sure.

**Comment by DarkenLX** [comment]
> @DarkenLX from what I read it had to do with the downloads of the games not being able to download because some configuration file or something like that I just can't remember where I read that at. It kinda sounded like it was fixable but I'm not sure.

Well tried to install it via the script still doesn't download games same issue it currently has.

**Comment by moraroy** [comment]
@DarkenLX I created another script to try and download the legacy games... via the logs, so basically, it reads the logs of what you tried to download and then downloads them but I can't get the launcher to detect my download...it deletes the game installer and won't register it in the launcher. Lol

**Comment by DarkenLX** [comment]
Yeah its really weird bug/issue this launcher has.. im wondering if its something to do with the way wine itself handles programs connecting to the internet through it or not. I don't know much on wines internal handling of these things.. but i wonder if theres a pass off or something like a middleman before the information is sent through the linux host machine's internet connection. Something similar to the idea of a firewall. And it's what causing this. Im guessing though since the WineHQ app database doesn't even have it listed they probably don't even know that it even has an issue or even exists.. lol

**Comment by DarkenLX** [comment]
> @DarkenLX I created another script to try and download the legacy games... via the logs, so basically, it reads the logs of what you tried to download and then downloads them but I can't get the launcher to detect my download...it deletes the game installer and won't register it in the launcher. Lol

Yeah that's probably a DRM thing that the launcher has even though most of the games are DRM free its the launchers way to make sure you own said game by it downloading it through the launcher.

**Comment by moraroy** [comment]
@DarkenLX @Localhorst86 this is been fixed finally, will be adding the scanner for it as well very soon.
