### ISSUE TITLE
Streaming apps do not work

### ISSUE THREAD

**Issue by PS2ClassicsVault** [moraroy/NonSteamLaunchers-On-Steam-Deck#91]
newest update does not auto force compatibility and when i do force them they will not launch i use Microsoft edge, i do not use google chrome cause chrome sucks and a big security risk with passwords cause every time i store my password in chrome they get compromised every time

Apps that add as a non steam  game does not work:

- Luna
- Netflix
- Hulu
- Disney+
- Xbox Gamepass
- Nvidia Geforce Now

you had it working fine before what happened?

**Comment by moraroy** [comment]
@PS2ClassicsVault I got rid of Microsoft edge entirely because it didn't make sense to have multiple browsers in the code. The only one that needed chrome was Amazon Luna, amazon Luna wouldn't work with anything else. So I figured the best thing to do would be consolidate and use just one web browser which is Chrome from the Disocvery Store. There is an alternative method I could do... instead of using a specific web browser for each one. I could make it so it launches whatever browser you have. This would only work in desktop modethough and you won't be able to do that in "Game Mode". In Game Mode, steam only opens its own web browser, which is based on chromium,  the problem is it doesn't have controller support and is very limited. As far as your passwords being stolen. I can't say why that is happening. You might want to check what's going on your system/wifi. I've never had that issue.

**Comment by moraroy** [comment]
@PS2ClassicsVault also do not force compatability on flatpaks!! All the streaming sites are not proton based. Leave the streaming sites "unchecked". Proton compatability will not launch a Linux bases program.

**Comment by PS2ClassicsVault** [comment]
well then that makes sens but either way kinda also sucks cause now i have to have two browser installed just to use them cause i use edge casue google lost my trust with securing password effeicently

**Comment by moraroy** [comment]
@PS2ClassicsVault I'll think about this a little more, but for now just use 2.96 for the edge shortcuts.

**Comment by mrmldeboy** [comment]
> @PS2ClassicsVault I'll think about this a little more, but for now just use 2.96 for the edge shortcuts.

How does one do this? When I download v2.96 and run the script (verified by file size) the window which pops up is v2.99.

**Comment by Mumpitz** [comment]
Do I get it right? The only thing these "Launchers" are starting is a Browser with the respective page of the streaming platform?
Why not using the actual apps? I mean its looking like it should work like the Battle.net launcher, no?
I know from Netflix, Prime and Disney+ that they have dedicated apps, at least for windows.
